In [1]:
import numpy as np

# 基础知识

## 创建数组

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([1,2.2,3])

array([1. , 2.2, 3. ])

In [4]:
np.array([1,2,3],dtype='float32')

array([1., 2., 3.], dtype=float32)

In [5]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## 数组的属性 

In [6]:
np.random.seed(0)
#设置随机数种子

In [7]:
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(2,3))
x3=np.random.randint(10,size=(2,3,4))
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2]
 [4 7 6]]
[[[8 8 1 6]
  [7 7 8 1]
  [5 9 8 9]]

 [[4 3 0 3]
  [5 0 2 3]
  [8 1 3 3]]]


#### 维度

In [8]:
x3.ndim

3

#### 维度大小

In [9]:
x3.shape

(2, 3, 4)

#### 数组总大小

In [10]:
x3.size

24

#### 数据类型

In [11]:
x3.dtype

dtype('int32')

## 数组的复制

In [12]:
x4=x3[:,:,2].copy()
print(x4)

[[1 8 8]
 [0 2 3]]


#### 直接使用切片会直接修改原本数组

## 数组的变形

In [13]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 数组的拼接

In [14]:
x=np.array([1,2,3,4,5,6]).reshape(2,3)
y=np.array([9,8,7,6,5,4]).reshape(2,3)

In [15]:
np.concatenate([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [16]:
z=np.concatenate([x,y],axis=1)
z

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4]])

## 数组的分裂

In [17]:
z=z.reshape(12)
z

array([1, 2, 3, 9, 8, 7, 4, 5, 6, 6, 5, 4])

In [18]:
z1,z2,z3,z4=np.split(z,[3,6,9])

In [19]:
z1

array([1, 2, 3])

In [20]:
z2

array([9, 8, 7])

In [21]:
z3

array([4, 5, 6])

In [22]:
z4

array([6, 5, 4])

# 计算通用函数

#### 顶层循环慢

### 普通运算效率基本一样

In [23]:
%timeit z1+z2

505 ns ± 32.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [26]:
%timeit np.add(z1,z2)

533 ns ± 22.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## 高级特性

### 指定输出

In [32]:
x=np.array(5)
y=np.empty(5)
np.add(x,10,out=y)
y

array([15., 15., 15., 15., 15.])

#### 没有临时数组，节省内存

### 聚合

In [28]:
np.add.reduce([z1,z2,z3,z4])
#连加

array([20, 20, 20])

In [29]:
z1

array([1, 2, 3])

### 存储中间结果

In [30]:
np.add.accumulate(z1)
#z1=[1,2,3]
#累加

array([1, 3, 6], dtype=int32)

### 外积

In [34]:
x=np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [31]:
np.add.at(z1,[0,2],3)
z1
#指定位置加
#改变原本！！！

array([4, 2, 6])

### 最大值

In [35]:
l=np.random.random(1000000)

In [37]:
%timeit sum(l)

10.8 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [38]:
%timeit np.sum(l)

2.89 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


两者并不等同！！！！

In [39]:
m=np.random.random((3,4))

In [45]:
m.shape

(3, 4)

In [41]:
m.sum()

5.5231112610000785

全部轴聚合

In [42]:
m.sum(0)

array([1.98939601, 1.00966293, 0.95070363, 1.57334869])

第一轴聚合

In [43]:
m.sum(1)

array([1.95867756, 2.1366976 , 1.4277361 ])

第二轴聚合

# 广播

## 规则1

维度不足左补一

In [2]:
m=np.ones((2,3))
a=np.arange(3)

In [4]:
m.shape

(2, 3)

In [5]:
a.shape

(3,)

In [6]:
m+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [7]:
(m+a).shape

(2, 3)

## 规则2

不匹配则拓展

In [8]:
a=np.arange(3).reshape((3,1))
b=np.arange(3)

In [9]:
a.shape

(3, 1)

In [10]:
b.shape

(3,)

In [11]:
(a+b).shape

(3, 3)

## 规则3

In [12]:
m=np.ones((3,2))
a=np.arange(3)

In [13]:
m.shape

(3, 2)

In [14]:
a.shape

(3,)

In [15]:
(m+a)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [17]:
a[:,np.newaxis].shape

(3, 1)

In [21]:
(m+a[:,np.newaxis]).shape

(3, 2)

# 花哨的索引

In [29]:
index=np.array([3,5,7,2]).reshape(2,2)
index

array([[3, 5],
       [7, 2]])

In [32]:
x=np.random.randint(100,size=10)
x

array([44, 94, 15,  9, 59,  4, 53, 61, 79,  0])

In [33]:
x[index]

array([[ 9,  4],
       [61, 15]])

形状与索引数组相同，而不是被索引数组

## 特殊

In [34]:
x=np.zeros(10)
x[[0,0]]=[4,6]

In [35]:
x

array([6., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

错误的用法

In [36]:
i=[2,3,3,4,4,4]
x[i]+=1

In [37]:
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

正确的用法

In [38]:
np.add.at(x,i,1)
x

array([6., 0., 2., 3., 4., 0., 0., 0., 0., 0.])

# 排序

副本

In [42]:
np.sort(x)

array([0., 0., 0., 0., 0., 0., 2., 3., 4., 6.])

原本

In [45]:
x.sort()
x

array([0., 0., 0., 0., 0., 0., 2., 3., 4., 6.])