In [1]:
from pandas import read_csv
from numpy import set_printoptions

In [2]:
target_url=r'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data=read_csv(target_url,header=None,names=['sepal length', 'sepal width','petal length', 'petal width', 'class'])
array=data.values

In [3]:
set_printoptions(precision=3)

In [4]:
array

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [5]:
X=array[:,:-1]
y=array[:,-1]

# 调整数据尺度

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
transformer=MinMaxScaler(feature_range=(0,1))
newX=transformer.fit_transform(X)

D:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
newX

array([[0.222, 0.625, 0.068, 0.042],
       [0.167, 0.417, 0.068, 0.042],
       [0.111, 0.5  , 0.051, 0.042],
       [0.083, 0.458, 0.085, 0.042],
       [0.194, 0.667, 0.068, 0.042],
       [0.306, 0.792, 0.119, 0.125],
       [0.083, 0.583, 0.068, 0.083],
       [0.194, 0.583, 0.085, 0.042],
       [0.028, 0.375, 0.068, 0.042],
       [0.167, 0.458, 0.085, 0.   ],
       [0.306, 0.708, 0.085, 0.042],
       [0.139, 0.583, 0.102, 0.042],
       [0.139, 0.417, 0.068, 0.   ],
       [0.   , 0.417, 0.017, 0.   ],
       [0.417, 0.833, 0.034, 0.042],
       [0.389, 1.   , 0.085, 0.125],
       [0.306, 0.792, 0.051, 0.125],
       [0.222, 0.625, 0.068, 0.083],
       [0.389, 0.75 , 0.119, 0.083],
       [0.222, 0.75 , 0.085, 0.083],
       [0.306, 0.583, 0.119, 0.042],
       [0.222, 0.708, 0.085, 0.125],
       [0.083, 0.667, 0.   , 0.042],
       [0.222, 0.542, 0.119, 0.167],
       [0.139, 0.583, 0.153, 0.042],
       [0.194, 0.417, 0.102, 0.042],
       [0.194, 0.583, 0.102, 0.125],
 

# 正态化数据

符合高斯分布的：线性回归、逻辑回归、线性判别分析

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
transformer=StandardScaler().fit(X)
newX=transformer.transform(X)

D:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [11]:
newX

array([[-9.007e-01,  1.032e+00, -1.341e+00, -1.313e+00],
       [-1.143e+00, -1.250e-01, -1.341e+00, -1.313e+00],
       [-1.385e+00,  3.378e-01, -1.398e+00, -1.313e+00],
       [-1.507e+00,  1.064e-01, -1.284e+00, -1.313e+00],
       [-1.022e+00,  1.263e+00, -1.341e+00, -1.313e+00],
       [-5.372e-01,  1.958e+00, -1.171e+00, -1.050e+00],
       [-1.507e+00,  8.007e-01, -1.341e+00, -1.182e+00],
       [-1.022e+00,  8.007e-01, -1.284e+00, -1.313e+00],
       [-1.749e+00, -3.564e-01, -1.341e+00, -1.313e+00],
       [-1.143e+00,  1.064e-01, -1.284e+00, -1.444e+00],
       [-5.372e-01,  1.495e+00, -1.284e+00, -1.313e+00],
       [-1.264e+00,  8.007e-01, -1.228e+00, -1.313e+00],
       [-1.264e+00, -1.250e-01, -1.341e+00, -1.444e+00],
       [-1.870e+00, -1.250e-01, -1.512e+00, -1.444e+00],
       [-5.251e-02,  2.189e+00, -1.455e+00, -1.313e+00],
       [-1.737e-01,  3.115e+00, -1.284e+00, -1.050e+00],
       [-5.372e-01,  1.958e+00, -1.398e+00, -1.050e+00],
       [-9.007e-01,  1.032e+00,

# 二值数据

01表示，在生成明确值或特征工程增加属性时使用

In [12]:
from sklearn.preprocessing import Binarizer

In [13]:
transformer=Binarizer(threshold=2.5).fit(X)
newX=transformer.transform(X)

In [14]:
newX

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],


# 特征工程

## 分类特征

In [15]:
data=[
    {'price':85,'rooms':4,'neighborhood':'queen'},
    {'price':70,'rooms':3,'neighborhood':'fre'},
    {'price':65,'rooms':3,'neighborhood':'wang'},
    {'price':60,'rooms':2,'neighborhood':'fre'},
]

In [16]:
from sklearn.feature_extraction import DictVectorizer
vec=DictVectorizer(sparse=False,dtype=int)
vec.fit_transform(data)

array([[ 0,  1,  0, 85,  4],
       [ 1,  0,  0, 70,  3],
       [ 0,  0,  1, 65,  3],
       [ 1,  0,  0, 60,  2]], dtype=int32)

In [17]:
vec.get_feature_names()

['neighborhood=fre',
 'neighborhood=queen',
 'neighborhood=wang',
 'price',
 'rooms']

In [18]:
vec=DictVectorizer(sparse=True,dtype=int)
vec.fit_transform(data)
#稀疏矩阵表示

<4x5 sparse matrix of type '<class 'numpy.int32'>'
	with 12 stored elements in Compressed Sparse Row format>

## 文本特征

In [19]:
sample=[
    'problem of evil',
    'evil queen',
    'horizon problem',
]

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

vec=CountVectorizer()
X=vec.fit_transform(sample)
X

<3x5 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [21]:
import pandas as pd

pd.DataFrame(X.toarray(),columns=vec.get_feature_names())

evil  horizon  of  problem  queen
0     1        0   1        1      0
1     1        0   0        0      1
2     0        1   0        1      0

频繁出现的词语会有很高的权重，通过TF-IDF改善

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

vec=TfidfVectorizer()
X=vec.fit_transform(sample)
pd.DataFrame(X.toarray(),columns=vec.get_feature_names())

evil   horizon        of   problem     queen
0  0.517856  0.000000  0.680919  0.517856  0.000000
1  0.605349  0.000000  0.000000  0.000000  0.795961
2  0.000000  0.795961  0.000000  0.605349  0.000000

## 图像特征